name: relio-app

services:
  relio:
    container_name: relio-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-}
      - CONFIG_PATH=/app/config/config.json
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./config:/app/config:rw
    restart: unless-stopped

