name: relio-app

services:
  relio:
    container_name: relio-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-}
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - relio_config:/app/config.json:rw
    restart: unless-stopped

volumes:
  relio_config:

